import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import Navbar from '@/shared/components/navbar';
import PageTransition from '@/shared/components/page-transition';
import './globals.css';

const nunito = Nunito({
    variable: '--font-nunito',
    subsets: ['latin'],
    weight: ['400', '600', '700', '800'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
    return (
        <html lang='en' className={`${nunito.variable} antialiased`}>
            <body className='min-h-screen flex flex-col w-full text-white'>
                <div
                    className='fixed inset-0 -z-20'
                    style={{
                        backgroundImage: "url('background.png')",
                        backgroundRepeat: 'no-repeat',
                        backgroundSize: 'cover',
                    }}
                />
                <div className='fixed inset-0 bg-black/50 -z-10' />
                <Navbar />
                <PageTransition>{children}</PageTransition>
            </body>
        </html>
    );
}
